### PR TITLE
Instruct @PlatformIO Crawler to use EspWifiService source code

### PR DESCRIPTION
**Pull request by ivankravets**
http://docs.platformio.org/en/latest/librarymanager/config.html#include

P.S: Please fix config for other manifests.

### CODE REVIEW

**Comment by jonathand131** [comment]
Hi, thanks for you remark.
Can you retry indexing ?
Thanks

**Comment by ivankravets** [comment]
Please fix [dependecies](http://docs.platformio.org/en/latest/librarymanager/config.html#dependencies) field in all libraries. See docs. It should not be array of library names. If you want to depend on any version, just use 

```json
    "dependencies": {
        "PCF8574_ESP": "*"
    },
```

instead of 

```
    "dependencies": [
        "PCF8574_ESP"
    ],
```

**Comment by ivankravets** [comment]
Thanks for the fixes. I see multiple errors for the Crawler. It says that you pointed to an invalid repository. 

```
    "repository": {
        "type": "git",
        "url": "https://github.com/jonathand131/EspLibs/EspCoreArchitecture"
    },
```

Try to open https://github.com/jonathand131/EspLibs/EspCoreArchitecture , what does Github say?

The valid repository for ALL manifests is a root repository, `https://github.com/jonathand131/EspLibs.git`. You control the offset source code via `export.include` field.

Please update all manifests and ping me here, I'll restart crawler for your manifests.

**Comment by jonathand131** [comment]
Hi, I have fixed the repository path. Is there a tool I can use to check the library.json files without bothering you ? Thanks for your support.

**Comment by ivankravets** [comment]
Thanks! All libs are added!

https://jsonformatter.curiousconcept.com

**Pull request merged**
